### ISSUE TITLE
13359 Segmentation fault

### ISSUE THREAD

**Issue by marselomeri** [nasa/cratous#4]
Hi, 
I was trying to run the demo examples and I ran into 'Segmentation fault' , you may see in the screen shot attached. 

Also, I don't really understand the logic of demo_lives, is there any explanatory documentation. 
Thanks

![Screenshot from 2019-09-17 19-01-10](https://user-images.githubusercontent.com/41054948/65063107-d473a980-d97d-11e9-9aaa-34ecb3187410.png)

**Comment by winstontssmith** [comment]
(One of the authors speaking)

I will need some time to take a real look at this since this week is very busy for me, but at first glance it looks like an issue on the UxAS side of things. The only solution I can think of immediately is to make sure you're running the scripts as root and to check your UxAS installation. It could also be something more tricky, but those are my suggestions for now. I'll get back to this as soon as I can to help you further.

**Comment by winstontssmith** [comment]
Lines 225-233 of https://github.com/afrl-rq/OpenUxAS/blob/ICAROUS_integration/src/UxAS_Main.cpp are outputting the error you're getting. This is almost certainly due to improper installation or use of UxAS. The specific error message says that permission was denied; please make sure UxAS directories and files have the proper permissions, and that it was installed properly.
